name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Balena engine version tag to build'
        default: ''
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'balena-os/balena-engine'
        ref: '${{ github.event.inputs.version }}'

    - name: Install github-release
      run: |
        sudo wget https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2 -O /usr/local/bin/github-release.bz2
        sudo bunzip2 /usr/local/bin/github-release.bz2
        sudo chmod 0755 /usr/local/bin/github-release

    - name: Build
      run: |
        make binary

    - name: Package
      run: |
        tar zcvf balena-engine-${{ github.event.inputs.version }}.tar.gz bundles/binary-daemon/*

    - name: Publish release
      run: |
        github-release release --user burmilla --repo os-balena-engine --tag ${{ github.event.inputs.version }} --pre-release --draft
        echo Waiting 30 seconds after release creation to make sure that GitHub is ready for uploads
        sleep 30s

        github-release upload --user burmilla --repo os-balena-engine --tag ${{ github.event.inputs.version }} --file balena-engine-${{ github.event.inputs.version }}.tar.gz --name balena-engine-${{ github.event.inputs.version }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.OS_RELEASE_TOKEN }}
